### ISSUE TITLE
Fail to create report and duplication of origin and destination when introducing ramp metering 

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#111]
Add ramp metering strategy e.g. fixed rate with queue control
Run simulation
Report is not created
Simulation does not run and the origin and destination of the route is duplicated 

![image](https://user-images.githubusercontent.com/60490284/89566555-5bc44880-d7ee-11ea-9bd6-0d3d7d77f48b.png)

**Comment by akurzhan** [comment]
fails in simulation with a caught exception:
class common.LaneGroupSet cannot be cast to class common.AbstractLaneGroup (common.LaneGroupSet and common.AbstractLaneGroup are in unnamed module of loader 'app')

After failure does not remove ghost pieces.

**Comment by akurzhan** [comment]
@ggomes I reassigned this issue to you.
