### ISSUE TITLE
Ramp meter rate and queue

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#120]
INCLUDE GHOST LINK VEHICLES WITH THE SOURCE ONRAMPS AND MAINLINE LINKS.

The calculation of the number of vehicles in the queue at the ramp seems that it is not correct. At the peak hours I have a demand of 1400 veh/hr and on purpose i am putting a ramp meter with a rate of 200 veh/hr. Hence the queue in 1 hour it should be 1200 vehs! However from the plot it is only 25 vehs. Hence, the queue does not spills till the beginning of the ramp and I can not test the queue overide.

![image](https://user-images.githubusercontent.com/60490284/90091224-db24b100-dcf3-11ea-8467-a76f15b90dd8.png)

**Comment by ggomes** [comment]
Fixed -- we are now counting vehicles in the source ghost link.
