### ISSUE TITLE
Different results for same configurations 

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#129]
I have 2 scenarios with exact same configurations. However the first has 3 commodities and the second has 2 commodities.

I would expect to have exactly the same results. However the results are completely different.
For example the contour plot is much different.

![image](https://user-images.githubusercontent.com/60490284/90536980-c3618880-e14a-11ea-8c79-349e49d803c9.png)
![image](https://user-images.githubusercontent.com/60490284/90537075-e1c78400-e14a-11ea-8822-be87b4ca2fd0.png)

**Comment by ggomes** [comment]
This may have to do with the fact that traffic in ghost links is not reported. I will check back again after correcting that problem.

**Comment by ggomes** [comment]
This was due to two things. First ghost sources not being recorded. Second, no cool down period.
