### ISSUE TITLE
Adding inner on-ramp and off-ramp at a section where we have a seperated HOV lane

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#131]
When adding inner on-ramp and off-ramp at a section where we have a seperated HOV lane, completely messes up the simulation results.
I believe we should not allow the creation of inner ramps whenever we have seperated HOV lanes

![image](https://user-images.githubusercontent.com/60490284/90655679-d8541f80-e20f-11ea-9086-cb8eb2874995.png)

**Comment by ggomes** [comment]
This is due to the offramp and barrier. 
There are vehicles that must reach the offramp and cannot because of the barrier. 
They stop at the downstream edge of the link and block all traffic. 
**I suggest we prohibit the combination of barrier and inner offramp in a single link..**

**Comment by ggomes** [comment]
This prohibition is at the UI level. I am removing myself from this issue.

**Comment by lapardhaja** [comment]
@akurzhan @ggomes This is related to issue 217
