### ISSUE TITLE
Speed calculation with metering

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#132]
When I have an on-ramp from fw1 which is connected with the off-ramp of fw2 and I introduce a ramp metering such as fixed rate. When the metering starts limiting the output flow from the the ramp, the speeds on the ramp drop significantly. The introduction of ramp metering to ramps which are not connected does not introduce such a problem.

So something seems it is not right.

![image](https://user-images.githubusercontent.com/60490284/90662270-2835e500-e216-11ea-9d2d-ccbd685163a3.png)

**Comment by ggomes** [comment]
I don't understand the problem here. 
The speed decreases because there are excess vehicles on the onramp.
