### ISSUE TITLE
Off-Ramp HOV lane

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#145]
When I have an off-ramp with GP lane and HOV lane, the vehicles use both lanes.

![image](https://user-images.githubusercontent.com/60490284/91323757-199b8080-e776-11ea-8658-6db33acdc775.png)

**Comment by ggomes** [comment]
The vehicles now only use the GP lane

**Comment by lapardhaja** [comment]
It is not resolved yet I still get the same issue

**Comment by ggomes** [comment]
You are right, I dont know what I was looking at when I saw vehicles only in the GP lane. In any case, this is the desired behavior right now. Look at our arrangement of road connections:
![image](https://user-images.githubusercontent.com/1287509/94303839-539da500-ff23-11ea-9bac-89c087c07651.png)
Once we implement HOV restrictions, we should see vehicles leaving the HOV lane immediately in the first cell of the offramp.

**Comment by ggomes** [comment]
@sevilap29 I believe I have fixed this problem in the newly deployed OTM. Please check.
