### ISSUE TITLE
Total flow does not add up to demand in free-flow conditions

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#146]
The flow from AUX lane and GP lanes does not addup to the total demand in free flow conditions. The measured flow is higher than the demand itself which is wrong.
![image](https://user-images.githubusercontent.com/60490284/91327426-59fcfd80-e77a-11ea-8ae5-cd1b3f296bf6.png)

**Comment by ggomes** [comment]
This is now ok.
