### ISSUE TITLE
Closed loop freeway

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#149]
Abnormal behavior when I have a closed loop (A-B-C-A) freeway where I input the vehicles from an on-ramp. Even though my capacity is higher than the demand there is a queue created on the ramp. The results do not seem right

![image](https://user-images.githubusercontent.com/60490284/91756435-94530a00-eb81-11ea-8df7-0a2be1cdd594.png)

**Comment by lapardhaja** [comment]
We should look why the speed increases at 2.5h and why the demand on the ramp remains about 8000 even though I input only for 1h. @ggomes

**Comment by ggomes** [comment]
I no longer see a problem at 2.5h.
