### ISSUE TITLE
Off-ramp flow

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#151]
Despite the fact that I have set that I want to have traffic split for 9 hours, the algorithm assumes that for the whole 24h we have that traffic split even though I have not set it. Perhaps we should assume that if I do not input anything it is 0% instead of grabbing the last traffic split ratio that it is set?

![image](https://user-images.githubusercontent.com/60490284/92022231-ce521680-ed0f-11ea-88cc-0731fe772b71.png)
![image](https://user-images.githubusercontent.com/60490284/92022248-d3af6100-ed0f-11ea-8306-cc6ed1e4021d.png)

**Comment by ggomes** [comment]
I think assuming the split to hold is better. To turn off the split, add a row with split = 0.
For example, in your table you could delete all but the first row.
