### ISSUE TITLE
Additional parameter in ControllerPolicyHOVHOT

### ISSUE THREAD

**Issue by akurzhan** [ucbtrans/opt#157]
I've added an additional param to `ControllerPolicyHOVHOT`: `**qos_speed_threshold_kph**`.
It is the quality of service speed threshold: when speed in a managed lane falls below this threshold, only free vehicle types are allowed in the managed lane, no tolled traffic. It is an equivalent to the infinite price.
For example, for HOT lanes in CA, this threshold is 45 mph. If the speed in an HOT lane drops below that, only HOVs are admitted.

**Comment by akurzhan** [comment]
Gabriel, please, just make sure this parameter is saved/retrieved to/from JAXB/XML.

**Comment by ggomes** [comment]
done
