### ISSUE TITLE
Vehicles not accumulating

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#160]
Despite having an increased on-ramp demand which would lead to congested conditions, vehicles are not accumulating on the on-ramp.

![image](https://user-images.githubusercontent.com/60490284/92977143-11636680-f441-11ea-81d7-704d2d908f3c.png)

**Comment by ggomes** [comment]
The onramp demand in this case (800 vph) does not exceed the onramp capacity (1400 vph), so one would not necessarily expect congestion on the onramp. The total demand (mainline plus onramp) does exceed the mainline capacity however. And we do see congestion in the upsream segment. This is appreciable in the delay plot.
