### ISSUE TITLE
Unreasonable spikes at timeseries

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#163]
When section length is significantly small the plots that are being produced are unreasonable. Maybe to put a length segment limit?

![image](https://user-images.githubusercontent.com/60490284/93524281-1dd83b00-f8e9-11ea-9abb-7d7e1276cc80.png)

**Comment by ggomes** [comment]
The program now throws an exception: "Simulation dt too small. This is likely caused by very short segments."
In this case, the dt was 0.55 seconds. 
I throw the exception whenever dt<1 second. 
If I increase the length of the segments to avoid the exception, then the problem disappears.
