### ISSUE TITLE
Flow on ML at on-ramp higher than GP lane

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#184]
The flow on the ML is twice as much as the flow on the GP at the on-ramp. I believe they should be equal so if the demand is 200 it should be 100 each.

![image](https://user-images.githubusercontent.com/60490284/95251318-30e77800-07d0-11eb-932c-3f9c8dd27633.png)

**Comment by ggomes** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/1287509/95929554-22253600-0d79-11eb-98fe-c4efe1591a3e.png)
