### ISSUE TITLE
Wrong plots when I have an inner and outer off-ramp

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#186]
![image](https://user-images.githubusercontent.com/60490284/95367147-3d7bd700-0889-11eb-90f5-78b90006863b.png)

**Comment by lapardhaja** [comment]
it might be related because we defined the flow and not split ratio

**Comment by lapardhaja** [comment]
Actually it is related because of that

**Comment by ggomes** [comment]
This is because the offramp flow controller is built assuming only one offramp. 
I will have to generalize this.
