### ISSUE TITLE
Off-ramp flow profile does not correspond to the input

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#193]
![image](https://user-images.githubusercontent.com/60490284/96294378-216ee880-0fa1-11eb-8fc0-4c14004d143b.png)
![image](https://user-images.githubusercontent.com/60490284/96294478-4a8f7900-0fa1-11eb-9e57-7c12b6aa3298.png)

**Comment by lapardhaja** [comment]
whenever I open the file it sets it to update period of 5 minutes and not 60 minutes I set it. It seems that it keeps in memory the 5min

**Comment by ggomes** [comment]
commit da2db78b8c72f74c2dd849d43c2fb5608b730a15 (HEAD -> master, ucbtrans/master)
Author: Gabriel Gomes <gomes@berkeley.edu>
Date:   Sun Oct 18 20:59:06 2020 -0700

    issue 193
