### ISSUE TITLE
use_fr_flows flag at off-ramps is not saved

### ISSUE THREAD

**Issue by akurzhan** [ucbtrans/opt#196]
It always saves as `use_fr_flows = true`.

**Comment by ggomes** [comment]
commit 27f54a69b51090422a48594928972d33497826eb (HEAD -> master, ucbtrans/master)
Author: Gabriel Gomes <gomes@berkeley.edu>
Date:   Sun Oct 18 21:20:19 2020 -0700

    issue 196
