### ISSUE TITLE
ML BARRIER

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#198]
When I put barrier seems like all the vehicles leave or something like that

without barrier:

![image](https://user-images.githubusercontent.com/60490284/96501057-a6a60780-1204-11eb-9436-dcba3737dae3.png)
![image](https://user-images.githubusercontent.com/60490284/96501067-adcd1580-1204-11eb-82b4-42d281406886.png)

with barrier:

![image](https://user-images.githubusercontent.com/60490284/96501113-c1787c00-1204-11eb-8e2d-c9cc9d3ebce3.png)
![image](https://user-images.githubusercontent.com/60490284/96501131-c76e5d00-1204-11eb-8e39-837a0be279d9.png)

**Comment by ggomes** [comment]
fixed with newly deployed OTM
