### ISSUE TITLE
Empty ML

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#200]
Empty managed lane for the segment before the removal of the ML lane
![image](https://user-images.githubusercontent.com/60490284/96504981-53cf4e80-120a-11eb-936f-93d5ce1aa986.png)

**Comment by ggomes** [comment]
This is the correct result. 
Vehicles in the ML  of segment D->E are all changing lanes out into the GP lane. Hence there is no longitudinal flow.
