### ISSUE TITLE
AUX lane weirdness

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#202]
Introduction of auxlane makes thing really weird.

Please check the testing networks that I sent and set the aux lane capacity to 1000

**Comment by ggomes** [comment]
It is hard to tell why this is happening. It has to do with the logit lane change model. It can be fixed by increasing the "lane keeping parameter" to about 1.8. I will suggest making that the default value unless and until I figure out the problem.

**Comment by ggomes** [comment]
new OTM
