### ISSUE TITLE
Flow dropping to 0

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#204]
Flow dropping to 0 despite having demand.

![image](https://user-images.githubusercontent.com/60490284/96634359-3c0dce00-12cf-11eb-977b-b4851db71478.png)

**Comment by ggomes** [comment]
@sevilap29 Please see my comment on issue 202

**Comment by lapardhaja** [comment]
even if i make it 1.8 or even higher this does not fix the problem @ggomes

**Comment by ggomes** [comment]
new OTM
