### ISSUE TITLE
Speed on ML equal to speed on GP

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#205]
Speed on ML equal to speed on GP despite having a different configuration for free flow speed.

**Comment by ggomes** [comment]
commit e1576bb9e57fa5c8df361517d029e9bea4f588fb (HEAD -> master, origin/master, origin/HEAD)
Author: Gabriel Gomes <gomes@berkeley.edu>
Date:   Wed Oct 21 12:18:55 2020 -0700

    issue 205
