### ISSUE TITLE
Vehicles in ML lane despite being banned

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#206]
According to the plot there are some vehicles in ML lane despite the fact I have banned them (e.g. LOV and Truck)

![image](https://user-images.githubusercontent.com/60490284/96635266-7f1c7100-12d0-11eb-8ff9-c6917253df89.png)

**Comment by ggomes** [comment]
@sevilap29  issue_204.opt in Slack does not have a policy defined.

**Comment by ggomes** [comment]
@akurzhan @sevilap29 
Probably same cause as #207
