### ISSUE TITLE
Total flow ML and GP not right when we have barrier and inner on-ramp

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#207]
If I put an inner on-ramp on a segment that has a barrier the total flow on my segment won't be as much as the total demand. Seems that the vehicles that are not HOV are being ignored when there is a barrier. If I don't have a barrier everything is fine.

Normally I would expect if there is barrier and inner on-ramp to have all the Vehicles in the ML lane until the barrier opens.

**Comment by ggomes** [comment]
@akurzhan @sevilap29 
I believe this is on the UI side. Specifically, in LinkPerformanceController line 800
![image](https://user-images.githubusercontent.com/1287509/96778483-9fb3fc00-13a0-11eb-81fc-933879317c7a.png)

should read xydata.mng...
