### ISSUE TITLE
Ramp Meter on ML does not work

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#208]
Ramp meter (e.g. fixed) does not work on ML. I set a very low rate of 10veh/h. However the flow on the ramp meter at the ML is significantly higher.

![image](https://user-images.githubusercontent.com/60490284/96637189-32866500-12d3-11eb-8e10-5a4982f9401c.png)

**Comment by ggomes** [comment]
@akurzhan @sevilap29 
The minimum and maximum metering rate settings are provided by .opt.prf, but they are invisible to the user.
In this case you are setting the metering rate to something that is below the minimum (which is 320), and hence it looks like an error.
