### ISSUE TITLE
Fixed Ramp metering not working properly

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#209]
I set the rate to be 75 veh/h but I see a flow of 150 on the GP lane of my on-ramp.

The metering is not following the rate I am providing.

![image](https://user-images.githubusercontent.com/60490284/96637792-09b29f80-12d4-11eb-9b88-7bf85c727abe.png)

**Comment by ggomes** [comment]
@akurzhan @sevilap29 
Same as 208

**Comment by lapardhaja** [comment]
@ggomes @akurzhan Despite the fact that the minimum is 320 why the flow then is 150?
