### ISSUE TITLE
Wavy flow on ML of on-ramp when ramp meter introduced on GP

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#210]
![image](https://user-images.githubusercontent.com/60490284/96638114-847bba80-12d4-11eb-8c51-ce0136b8eb19.png)

**Comment by ggomes** [comment]
new OTM

**Comment by lapardhaja** [comment]
@ggomes The issue still remains, now the plot looks like this:
![image](https://user-images.githubusercontent.com/60490284/96801347-393cd700-13bc-11eb-9670-dc51fa5e0961.png)
