### ISSUE TITLE
Vehicle queue - ramp metering

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#211]
If I have an on-ramp 1 GP lane and 1 ML with mostly HOV vehicles. If I set ramp metering on both lanes, I have an accumulation of vehicle queue only on the GP lane but not on the ML lane.

I discussed this with @akurzhan and he explained me that this is because of the ghost links. 

I think we need to think about this issue what needs to be done.

![image](https://user-images.githubusercontent.com/60490284/96833309-10850380-13f5-11eb-800e-3aeb4df7b74c.png)

**Comment by ggomes** [comment]
commit 55d299d1b601d288f2621caf4abdccfedce35919 (HEAD -> master, origin/master, origin/HEAD)
Author: Gabriel Gomes <gomes@berkeley.edu>
Date:   Fri Oct 23 14:01:55 2020 -0700

    issue 211
