### ISSUE TITLE
Discrepancy in the speed

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#216]
If I have the same exactly configuration between 2 scenarios but on the segment upstream on the first scenario I have a barrier and on the segment downstream I will have reduction of speed of speed at the ML.

However If upstream there is no barrier I do not observe this phenomenon.

I am expecting both to not have reduction of speed.
![image](https://user-images.githubusercontent.com/60490284/97033570-64d4d400-1518-11eb-8eb1-b2f8056f16df.png)
![image](https://user-images.githubusercontent.com/60490284/97033608-78803a80-1518-11eb-8d03-bd40a41d133e.png)

**Comment by ggomes** [comment]
new OTM

(base) gomes@ggss:~/code/opt$ git log -1
commit 3f76c05bcbf082d57cd0a24be02867a5d4ca9aa4 (HEAD -> master, origin/master, origin/HEAD)
Author: Gabriel Gomes <gomes@berkeley.edu>
Date:   Sat Oct 24 23:08:07 2020 -0700

    use dwn vehicles for speed calculation
