### ISSUE TITLE
Flows do not make sense

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#220]
![image](https://user-images.githubusercontent.com/60490284/97650460-f2cc2580-1a16-11eb-8e73-c68b048a7501.png)

**Comment by ggomes** [comment]
The problem here is that some of the HOV vehicles are choosing to use the GP lane even though there is a queue there, and the none in the ML. The result is that the ML is underutilized, so HOV vehicles are delayed without need. The solution will be to improve the lane selection model on onramps.

**Comment by ggomes** [comment]
Can you please expand on this?

**Comment by lapardhaja** [comment]
I have a demand of about 5000 veh/h but the flow that I am getting is at 2000 veh/h. And I do not have congested conditions...

**Comment by ggomes** [comment]
@sevilap29  This is very strange. This is the picture I get with issue_220.opt
![image](https://user-images.githubusercontent.com/1287509/97907356-08349e80-1cfa-11eb-8ea2-1152a70c1869.png)

**Comment by lapardhaja** [comment]
seems resolved now:
![Uploading image.png…]()
