### ISSUE TITLE
Error message when I have inner off-ramp and barrier is not appearing

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#221]
Error message when I have inner off-ramp ,HOV and barrier is not appearing. I remember you had said that a error message should pop up

**Comment by ggomes** [comment]
commit a09f13d96dd24a99f6decbc299ebd048d2b7a1b7 (HEAD -> master, ucbtrans/master)
Author: Gabriel Gomes <gomes@berkeley.edu>
Date:   Fri Oct 30 09:59:10 2020 -0700

    issue 221
