### ISSUE TITLE
GP veh queue when ramp metering is wrong

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#223]
![image](https://user-images.githubusercontent.com/60490284/97730549-3ebbb080-1a91-11eb-9fac-ad14ff6918de.png)

**Comment by ggomes** [comment]
The problem here is that HOVs are choosing the GP lane even though there is a large queue there and none in the ML. 
The solution will be to improve the lane selection model on onramps.

**Comment by lapardhaja** [comment]
LOVs also are choosing the ML lane! even though they should not be supposed to I think
