### ISSUE TITLE
Closing GP lane makes flow even at ML 0

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#226]
![image](https://user-images.githubusercontent.com/60490284/97731458-5e9fa400-1a92-11eb-8ffa-22489f8919e2.png)
![image](https://user-images.githubusercontent.com/60490284/97731471-65c6b200-1a92-11eb-97e2-f2a611faaae6.png)

We should have 0 flow on ML and there should not be a queue there

**Comment by ggomes** [comment]
![image](https://user-images.githubusercontent.com/1287509/97743534-0de47700-1aa3-11eb-84d8-2aec351fcaaa.png)

The ML lane is actually getting block by vehicles that try to change lanes ML->GP but are unable to because of the queue in the GP lane.
