### ISSUE TITLE
Flow on off-ramp higher than the one I set

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#230]
Flow on the off-ramp is higher than the one I set it to be (1000 veh/h)
![image](https://user-images.githubusercontent.com/60490284/98019578-c87fbc80-1db6-11eb-8a31-ca5590396ab5.png)

**Comment by ggomes** [comment]
New OTM version deployed

commit 1285e613a08a5609c7ac4e861dbc45161ed254e0 (HEAD -> master, origin/master, origin/HEAD)
Author: Gabriel Gomes <gomes@berkeley.edu>
Date:   Thu Nov 5 21:43:41 2020 -0800

    fix issue 230
