### ISSUE TITLE
Barrier and outer off-ramp weird results

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#231]
Having barrier and outer off-ramp generates really weird results.
![image](https://user-images.githubusercontent.com/60490284/98020542-fd404380-1db7-11eb-87b7-6aa648784fd9.png)

**Comment by ggomes** [comment]
NEW OTM 
commit d27d3a54067b4950bdbacaa94bb3cd6d855f2ad7 (HEAD -> master, origin/master, origin/HEAD)
Author: Gabriel Gomes <gomes@berkeley.edu>
Date:   Fri Nov 6 09:08:11 2020 -0800

    issue 231
