### ISSUE TITLE
Set ramp meter starting at 00:00

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#232]
If ramp meter starts at 00:00 the results are weird
![image](https://user-images.githubusercontent.com/60490284/98021355-1695bf80-1db9-11eb-9d93-63e18cbd57d3.png)

If it starts at 1:00 or any other time it is fine

**Comment by ggomes** [comment]
fixed with issue 231

**Comment by ggomes** [comment]
@sevilap29 
The results no longer look like what you show here. I'm not sure why, since the fix for 231 had nothing to do with ramp metering. Can you please check this again and let me know (or close the issue)?

**Comment by lapardhaja** [comment]
@ggomes I don't have that issue anymore. I dont know how it got fixed
