### ISSUE TITLE
Simulation does not work properly when I have 1 inner off - ramp and 2 outer

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#239]
If I have 1 inner off-ramp and 2 outer off-ramps simulation does not run well.

![image](https://user-images.githubusercontent.com/60490284/98426192-c46ccc80-204c-11eb-90f4-c78aaa2ca9ae.png)

**Comment by ggomes** [comment]
This is what I am seeing:

![image](https://user-images.githubusercontent.com/1287509/98471813-b087ae80-21a3-11eb-82cf-c6a9d7128a9b.png)

**Comment by ggomes** [comment]
Indeed, looks like an issue with the node model. I will be able to fix this on 11/11.
