### ISSUE TITLE
Not observing flow on off-ramp

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#240]
I have an off-ramp and I am not observing flow exiting from it. I do not know why is this happening.

**Comment by lapardhaja** [comment]
If you set the start time at 00:00 for the simulation then we are going to have off-ramp flows but if the start time is set something else other than 0 we are not going to have off-ramp flows.

**Comment by ggomes** [comment]
fixed in opt branch frcntrl and new OPT
use issue_240_new.opt
