### ISSUE TITLE
Small spikes of flow at off-ramp

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#241]
Small spikes of flow at off-ramp when the we input the flow (no split ratios). Also everytime a new value of flow is inserted there are some small spikes.

![image](https://user-images.githubusercontent.com/60490284/99605548-bf007200-29bc-11eb-8fb4-7e3ba27b6d70.png)

**Comment by ggomes** [comment]
fixed in opt branch frcntrl and new OPT
use issue_241_new.opt
