### ISSUE TITLE
Ramp meter rate

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#242]
Ramp meter is not giving me the rate I am inputing.

I set 1200 veh/hr as rate but it applies around 900

![image](https://user-images.githubusercontent.com/60490284/99743261-2e906300-2a8a-11eb-9c0d-46df1b611895.png)

**Comment by ggomes** [comment]
This is due to congestion that is coming from downstream. 
Notice that the problem disappears if you delete the last two segments.
