### ISSUE TITLE
Canceling simulation - must discard incomplete simulation data

### ISSUE THREAD

**Issue by akurzhan** [ucbtrans/opt#245]
When I cancel the simulation, I expect that no simulation data is assigned to the scenario.
Currently, incomplete data are assigned. This causes exceptions when reports try to open.

**Comment by ggomes** [comment]
commit 8cceaf63f76cabab0605cf493e9b438fb2dd0bdb (HEAD -> master, origin/master, origin/HEAD)
Author: Gabriel Gomes <gomes@berkeley.edu>
Date:   Wed Dec 2 14:03:12 2020 -0800

    implement cancel in OTMTask
