### ISSUE TITLE
Can't run simulation after stopping it

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#246]
Please check uploaded video for this issue

**Comment by lapardhaja** [comment]
Actually seems like the simulation is not canceled, even though it should be. Seems like it runs on the background

**Comment by ggomes** [comment]
@akurzhan Servet is closing the window and not hitting the cancel button. You should cancel the run if the window is closed.

**Comment by ggomes** [comment]
looks ok to me
