### ISSUE TITLE
Uniform flow across different lane groups when I have 1 commodity

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#247]
Uniform flow across different lane groups when I have 1 commodity
e.g. expecting 1000 veh/h in GP and 1000 veh/h in ML

![image](https://user-images.githubusercontent.com/60490284/101099777-3b2cb500-357a-11eb-8b46-aa600265d165.png)

**Comment by lapardhaja** [comment]
I think we discussed this yesterday. I am just adding it as a reminder

**Comment by ggomes** [comment]
Flow on lanes is now proportional to capacities, so this case should now work as expected.
