### ISSUE TITLE
Expecting 0 delay at Free flow

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#248]
I am expecting the delay to be 0 at free flow conditions. Maybe there is something wrong in the calculation?

![image](https://user-images.githubusercontent.com/60490284/101100181-e9d0f580-357a-11eb-9d52-07ed6d20451d.png)

**Comment by lapardhaja** [comment]
This is happening when I have HOV lane despite I ban the vehicles. If I remove the HOV lane then the delay is 0

**Comment by ggomes** [comment]
The cause of this is that the "flow" in the formula for delay does not include the lane changing flow. If, for example, everyone changes lane, then the longitudinal flow is zero, even though vehicles are moving (sideways), and hence delay is overestimated. 
Possible solutions:
a) only include longitudinally moving vehicles in the "vehicles" of the delay formula.
or
b) collect and include lane changing flows in the "flows" of the delay formula.

**Comment by ggomes** [comment]
New OTM. Use `issue_248_a.opt`
