### ISSUE TITLE
AUX lane queue on mainline

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#249]
Queue at AUX lane even though I do not have a ramp. I am expecting that I should not have any vehicle there since there is no ramp. However, there is a formation of queue

![image](https://user-images.githubusercontent.com/60490284/101194732-39fb9680-3613-11eb-8318-2f99c76ca6f0.png)

**Comment by ggomes** [comment]
(base) gomes@ggss:opt$ git log -1
commit a7d29349a52c23b73bc21e012fe9e42e71873be7 (HEAD -> master, origin/master, origin/HEAD)
Author: Gabriel Gomes <gomes@berkeley.edu>
Date:   Mon Dec 7 14:56:51 2020 -0800

    issue 249
