### ISSUE TITLE
Off-ramp split ratio

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#250]
If I set split ratio 10% at an off-ramp and my mainline is for 5000, i am expecting 500 on the off-ramp. So it is practically calculated based on the mainline flow.

However, if I have an off-ramp with flows and an off-ramp with split ratios, I see that the calculation is (Mainline-off-ramp flow)*10%

Is that normal or not? Shouldn't we calcualte the split ratio based on the mainline?

**Comment by ggomes** [comment]
The (arbitrary) rule we are following is that off-ramp flows are removed first, and then the split is applied to that. So in this case, where you have an offramp with offramp flow of 2000 vph, the 10% is applied to 5000-2000 = 3000, and so you get offramp flow of 300vph.
