### ISSUE TITLE
No flow on off-ramp

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#251]
If I have 2 off-ramps with specified flows, I can not observe flow on one of them (0 flow). And for an unusual reason the off-ramp that has 0 flow, sets the off-ramp profile for the off-ramp that has flow. 

![image](https://user-images.githubusercontent.com/60490284/101197306-c9ef0f80-3616-11eb-8685-7ccb9df0a54c.png)
![image](https://user-images.githubusercontent.com/60490284/101197316-d2474a80-3616-11eb-9d92-5bf96ae7d579.png)
![image](https://user-images.githubusercontent.com/60490284/101197346-db381c00-3616-11eb-85a3-41dae568d325.png)
![image](https://user-images.githubusercontent.com/60490284/101197375-e428ed80-3616-11eb-868f-95cc820e5460.png)

**Comment by ggomes** [comment]
NEW OTM + OPT pull

commit 40ebbbcd85eea4c008562168ca35ee460a61aae8 (HEAD -> master, origin/master, origin/HEAD)
Author: Gabriel Gomes <gomes@berkeley.edu>
Date:   Tue Dec 8 13:18:43 2020 -0800

    issue 251
