### ISSUE TITLE
Drop of flow on mainline when I have AUX lane

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#252]
Unreasonable drop of flow on the mainline when I have an AUX lane, despite the fact that capacity is by far higher than the demand

![image](https://user-images.githubusercontent.com/60490284/101204050-78e41900-3620-11eb-930f-5d5ff75a35c8.png)

**Comment by ggomes** [comment]
This is because the flow to the offramps is very high and so there is a lot of mandatory lane changing. Try it again with lower offramp flows
