### ISSUE TITLE
Observing flow in ML despite banning the commodity

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#253]
![image](https://user-images.githubusercontent.com/60490284/101204527-353ddf00-3621-11eb-883b-84a908f507c6.png)
![image](https://user-images.githubusercontent.com/60490284/101204544-3bcc5680-3621-11eb-916d-a4312566fdf8.png)
![image](https://user-images.githubusercontent.com/60490284/101204559-42f36480-3621-11eb-98e8-9d22bd068bb2.png)

**Comment by ggomes** [comment]
This is because the barrier prevents them from leaving. 
To avoid this one must add an upstream segment without the barrier and put that segment into the policy.
