### ISSUE TITLE
AUX lane empty

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#254]
Despite having an on-ramp and an AUX lane, the AUX lane is empty.
According to your document if I have an AUX lane then on-ramp should be connected to it

![image](https://user-images.githubusercontent.com/60490284/101205375-610d9480-3622-11eb-9602-06d9ba3f572d.png)

![image](https://user-images.githubusercontent.com/60490284/101205321-4f2bf180-3622-11eb-819a-0824b3cbd7ac.png)

**Comment by ggomes** [comment]
This flow does not include lane changing vehicles. 
All vehicles in the aux lane in this situation are changing lanes.
