### ISSUE TITLE
AUX lane flow

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#257]
Add AUX lane with on and off-ramp using split ratio. Expecting to see 600 veh/hr on the off-ramp and 1000 on the AUX lane.

However I only see 600 veh/hr on the aux-lane which is practically the flow of vehicles leaving. Shouldn't we see also the vehicles entering from on-ramp at the aux?

**Comment by ggomes** [comment]
use issue_257a

**Comment by ggomes** [comment]
The flow reported for the AUX lane is what *exits* the aux lane, ie the offramp flow.

**Comment by lapardhaja** [comment]
The flow at the off-ramp seems wrong. It is only 500 veh/hr. It should be 600 which is 10% of 6000(5000 from mainline and 1000 from on-ramp).

**Comment by ggomes** [comment]
I will address this on slack.
