### ISSUE TITLE
OPT Events

### ISSUE THREAD

**Issue by akurzhan** [ucbtrans/opt#258]
We have to implement UI for 4 events:
1. Change lane numbers in links' lane groups;
2. Change fundamental diagrams in links' lane groups;
3. Close/ open off-ramps - semantically, it is the same as turning capacity to 0 in the previous event, but we need to distinguish it for the UI purpose. 
4. Turn control off/ on.

Events happen instantly at the user-specified time of their activation.
Each event makes changes to a set of targets. A target can be either a lane group or a control schedule.

### Generic event properties
* ID;
* Name - needed for UI purposes;
* Target type - lane group, control schedule and maybe something else in the future;
* Time in seconds - when in simulation the event is activated (if the time event is outside the time of simulation - before start time or after end time = start + duration, then the event is never activated).

**First of all, we need a facility to save/load OPT files with events - XSD must be modified.**

Each event also has its own properties.

### Lane change event
* A map: lane group -> target

### Fundamental diagram change event
* A map: lane group -> FD (free flow speed, capacity per lane and jam density per lane)

### Off-ramp closure event
* A map: lane group -> boolean flag: closed = True / False

### Control toggle event
* A map: control schedule -> boolean flag: on / off

**Comment by akurzhan** [comment]
For each type of events we need:
* add function
* delete function
* public access or getters/setters for event parameters

Also: for each event type, we have a _Map_<target, parameter>.
Depending on the event type, target is a lane group or a control schedule; and parameter is int, boolean, or FDparams.
Right now, in the proposed API you have a single value, not a _Map_<target, parameter>.

**Comment by ggomes** [comment]
# API
**Notes**: 

- In `EventLanegroupLanes`, `delta_lanes` is a change in the number of lanes. 
- In `EventLanegroupFD`, `fdmult` contains positive multipliers for the fundamental diagram.
- In both of these cases passing `delta_lanes=null` or `fdmult=null` means "return to nominal values"

## EventLinkToggle
`public EventLinkToggle add_event_linktoggle(float timestamp, String name, List<AbstractLink> links, boolean isopen) throws Exception `

## EventControlToggle
`public EventControlToggle add_event_controltoggle(float timestamp, String name, List<ControlSchedule> controllers, boolean ison) throws Exception `

## EventLanegroupLanes
`public EventLanegroupLanes add_event_lglanes(float timestamp, String name, List<AbstractLink> links, LaneGroupType lgtype, Integer delta_lanes) throws Exception `

**Notes**: 
- `delta_lanes` is a change in the number of lanes. 
- `delta_lanes=null` means "return to nominal values"

## EventLanegroupFD
`public EventLanegroupFD add_event_lgfd(float timestamp, String name,List<AbstractLink> link,LaneGroupType lgtype,FDparams fdmult) throws Exception `

**Notes**: 
- `fdmult` contains positive multipliers for the fundamental diagram.
- `fdmult=null` means "return to nominal values"

**Comment by ggomes** [comment]
# Creating events
## From FreewayScenario
- `public EventLinkToggle add_event_linktoggle(float timestamp, String name, List<AbstractLink> links, boolean isopen) throws Exception `
- `public EventControlToggle add_event_controltoggle(float timestamp, String name, List<ControlSchedule> controllers, boolean ison) throws Exception `
- `public EventLanegroupLanes add_event_lglanes(float timestamp, String name, List<AbstractLink> links, LaneGroupType lgtype, Integer delta_lanes) throws Exception `
- `public EventLanegroupFD add_event_lgfd(float timestamp, String name,List<AbstractLink> links,LaneGroupType lgtype,FDparams fd_mult) throws Exception `


# Deleting events
## From FreewayScenario
- `public void delete_event_by_id(long eventid)`

## From AbstractLink
(nothing here)

## From ControlSchedule
(nothing here)

# Modifying events

## AbstractEvent (applies to all events)
- `id` and `type` are final (they cannot be changed)
- `timestamp` and `name` are public (change them directly)
## EventLinkToggle
- `public void add_link(AbstractLink x)`
- `public void remove_link_by_index(int i)`
- `public void remove_link(AbstractLink x)`
## EventControlToggle
- `public void add_controller(ControlSchedule x)`
- `public void remove_controller_by_index(int i)`
- `public void remove_controller(ControlSchedule x)`

## AbstractEventLaneGroup (applies to EventLanegroupLanes and EventLanegroupFD)

- `public void add_link(AbstractLink x) throws Exception `
- `public void remove_link_by_index(int i)`
- `public void remove_link(AbstractLink x)`
- `public LaneGroupType get_lgtype()`
- `public void set_lgtype(LaneGroupType lgt) throws Exception `


## EventLanegroupLanes
`delta_lanes` is public

## EventLanegroupFD
- `public void set_fdmult_to_null()`
- `public void set_capacity_mult(float x)`
- `public void set_jamdensity_mult(float x)`
- `public void set_ffspeed_mult(float x)`
