### ISSUE TITLE
Features for the next User Group Webinar

### ISSUE THREAD

**Issue by akurzhan** [ucbtrans/opt#26]
During the next webinar, we'd like to have:
- Road parameters (capacity, free flow speed, jam density) - set for GP, managed and aux lanes.
- Demand for multiple commodities - will be implemented as JavaFX table with copy/paste functionality.
- Split ratios for off-ramps. How to implement UI in a table?
- On-ramp priorities.
- Vehicle types - on scenario level.

**Comment by ggomes** [comment]
On deleting commodities: "comm" branch, see FreewayScenario.delete_commodity_with_name() and FreewayScenario.delete_commodity_with_id()

**Comment by ggomes** [comment]
What do you mean be "Vehicle types - on scenario level."?
