### ISSUE TITLE
inner_outer_off_ramp test

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#263]
The inner off-ramp flow is wrong. I should expect 2000 and for some reason it is only 600. Independent of what value I put for the off-ramp flow it is stuck to 600 veh/hr.

![image](https://user-images.githubusercontent.com/60490284/104205530-839e8480-53fc-11eb-979b-26ae2f27fd91.png)

**Comment by ggomes** [comment]
There are now 2000 vph, split between GP and MN lanes
