### ISSUE TITLE
off-ramp flow

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#265]
Off-ramp flow is 0 when I create an off-ramp at a segment where I have an on-ramp, and for the off-ramp I select off-ramp flow (not the split ratio).

![image](https://user-images.githubusercontent.com/60490284/104232063-c58bf280-541d-11eb-80df-c8b011328eb8.png)

**Comment by lapardhaja** [comment]
please look also at issue @266

**Comment by ggomes** [comment]
new OTM, use issue_265_a.opt
