### ISSUE TITLE
Circular road congestion

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#267]
I am making a circular road and assigning 2000 veh/hr for just 1 hour ( after that I set the demand at the on-ramp to be 0). So I am expecting to have only 2000 veh/hr in my road. However I am having congestion for some reason which I should not have. Is there a bug or am I doing something wrong?

![image](https://user-images.githubusercontent.com/60490284/104237585-42bb6580-5426-11eb-8cc7-3c4f6fbfec3a.png)

**Comment by ggomes** [comment]
The problem here is that the ring is too small. Each of the 3 links is about 100 meters long, so at 100 kph vehicles circulate 333 time in the hour of 2000 vph demand, adding up to 333*2000 = 666,000 vph!
