### ISSUE TITLE
Split flows by half at on-ramp

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#273]
Expecting to split the flow by half if I have an on-ramp with 1 ML and 1 GP and the ML is open to all. Hence I expect to have 500/500, which is not the case here.

![image](https://user-images.githubusercontent.com/60490284/105747779-10b20500-5ef6-11eb-8c07-d5b877d4d4fc.png)

**Comment by ggomes** [comment]
Flows are split in proportion to capacities. Here GP has 2000 vs ML has 1800, so GP receives larger flow.
