### ISSUE TITLE
Change of lanes for small portion coming from on-ramp

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#274]
If flow comes only from on-ramp, and not mainline, I expect in the segment that the on-ramp is, the whole flow to be on the GP lane. This actually happens.

However, at the segment downstream I may expect either the flow to be distributed among ML and GP (for example in this case to be 250 veh/hr in ML) or just to remain at the GP (you tell me how you want it to be). In our case none of them happens. For some reason there is a very tiny amount of vehs (8veh/hr) that goes to the ML.

![image](https://user-images.githubusercontent.com/60490284/105748069-74d4c900-5ef6-11eb-9509-610d6713e1e6.png)

**Comment by ggomes** [comment]
In this case no one is changing lanes into the ML  in the downstream segment, so the GP/ML flows are the same in B->C and in C->D. This lack of lane changes is due to the lane change model. I suspect there is no lane changing because the difference in supply is below the threshold. I'll check this.

**Comment by lapardhaja** [comment]
At B-C if I remember well the ML flow was 0, while here at C-D there is some

**Comment by ggomes** [comment]
Servet, please check again, the flows are identical. 
Note to self: use this to check the parameters of the lane change model.
