### ISSUE TITLE
Flow on ML at off-ramp even though I do not have an AUX lane

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#275]
According to your document, when I do not have an aux lane I should not observe any type of connection with the ML.

![image](https://user-images.githubusercontent.com/60490284/105749300-10b30480-5ef8-11eb-93ac-5954599c3e3b.png)
![image](https://user-images.githubusercontent.com/60490284/105749326-1a3c6c80-5ef8-11eb-9bc4-ed04bc090961.png)

![image](https://user-images.githubusercontent.com/60490284/105749391-32ac8700-5ef8-11eb-95e1-0f8606b6c79d.png)

**Comment by ggomes** [comment]
This may have been unclear. When there is no aux lane, then the GP lane on the freeway connects to both GP and ML on the offramp.
