### ISSUE TITLE
Expecting 0 flow downstream

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#276]
I am expecting 0 flow downstream cause all the vehicles have exited from an off-ramp upstream. However I observe some flow on the ML downstream of the off-ramp
![image](https://user-images.githubusercontent.com/60490284/105749625-861ed500-5ef8-11eb-92ea-609e60b0314f.png)

**Comment by ggomes** [comment]
Interesting. I wonder whether the ML is reporting cell-based quantities.

**Comment by ggomes** [comment]
new OTM
