### ISSUE TITLE
Adding barrier increases total flow more than demand

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#278]
Total observed flow is higher than the demand (input of vehicles) at the link where I have a barrier and an off-ramp. It should be noted that the off-ramp has 0 flow. I didnt make any vehicle to leave. My demand is 1000 and my total flow is 1250!
![image](https://user-images.githubusercontent.com/60490284/105750685-e9f5cd80-5ef9-11eb-9ccf-93878651a601.png)

**Comment by ggomes** [comment]
new OTM.
