### ISSUE TITLE
FreewayScenario.get_freeways() returns not all segments

### ISSUE THREAD

**Issue by akurzhan** [ucbtrans/opt#29]
Function `FreewayScenario.get_freeways()` misses the connector segments.
Use the example `opt/src/test/resources/EndResult.opt` to debug: connector I-580E -> I-80W connector is missing in the result returned by the function.

**Comment by ggomes** [comment]
This is the desired behavior. Recall that this function returns a list of linear freeways. It excludes ramps and connectors.
