### ISSUE TITLE
GP almost empty

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#293]
When I have the following configuration:
![image](https://user-images.githubusercontent.com/60490284/106203940-0485ac00-6171-11eb-8fa6-4315e18b7331.png)
The vehicles when they go on FW2 they remain on the HOV lane almost all of them. I know this is happening because it is not triggering a threshold that you have, but this is not a normal behavior so it needs to be looked at.
![image](https://user-images.githubusercontent.com/60490284/106204123-4d3d6500-6171-11eb-8a83-a8ab57f7f994.png)

**Comment by ggomes** [comment]
use issue293_fixed.opt
