### ISSUE TITLE
Vehicle queue and ramp meter

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#295]
I have the same ramp meter rate for both ML and GP, however their queues do not grow in the same way despite the fact they 2 lane groups are identical

**Comment by lapardhaja** [comment]
![image](https://user-images.githubusercontent.com/60490284/106642973-e5ef2e80-653d-11eb-83ab-947ecd437d9f.png)

**Comment by ggomes** [comment]
commit 2e8046eac7699afab4ea41dc8ff055af41e89755 (HEAD -> master)
Author: Gabriel Gomes <gomes@berkeley.edu>
Date:   Wed Feb 10 13:41:18 2021 -0800

    issue 295
