### ISSUE TITLE
Likely incorrect results

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#302]
I am not really sure about the results of the plots. I have GP and ML open for all, but for some reason after 1h despite having not changed anything for the demand and having congested conditions, the flow on the Managed Lanes drops.

![image](https://user-images.githubusercontent.com/60490284/107437729-46551180-6ae4-11eb-9035-fd70fed1277a.png)

**Comment by ggomes** [comment]
@sevilap29 Ramp metering goes to fixed rate at 1hr.

**Comment by ggomes** [comment]
@sevilap29 Please check this and close if it is fixed.
