### ISSUE TITLE
Bottleneck created with only 1 segment

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#309]
I have 1 segment only A-B, and I have 3GP and 1 ML with total capacity of 8000. I put 8000 demand, so I expect no congestion. This is true if I do not have an off-ramp at that segment. However If I have an off-ramp even if it is empty (0 split or flow) something happens to the segment and congestion is created.
![image](https://user-images.githubusercontent.com/60490284/107553853-07799700-6b8a-11eb-80e3-5e08173e1ecf.png)

**Comment by ggomes** [comment]
fixed in latest version

**Comment by lapardhaja** [comment]
Issue unresolved. Still remains

**Comment by ggomes** [comment]
commit 4d9876f92fa32aa9549f3553c3b1b10f172ee6d8 (HEAD -> master, ucbtrans/master)
Author: Gabriel Gomes <gomes@berkeley.edu>
Date:   Sat Feb 13 10:57:10 2021 -0800

    issue 309
