### ISSUE TITLE
Params for aux lanes are not saved in XML file

### ISSUE THREAD

**Issue by akurzhan** [ucbtrans/opt#33]
I can change parameters (capacity, free flow speed, jam density) for auxiliary lane. 
However, the changes are not recorded in the XML file.
Only aux lane parameters are affected.

**Comment by akurzhan** [comment]
@ggomes I am currently working in the `params` branch.

**Comment by ggomes** [comment]
@akurzhan I was not able to reproduce this problem in the UI.
