### ISSUE TITLE
demand percentages not applied

### ISSUE THREAD

**Issue by ggomes** [ucbtrans/opt#35]
I define 50% demand in the UI and see 100% in the XML.
![image](https://user-images.githubusercontent.com/1287509/66978672-b756f700-f05f-11e9-98f2-1e3876840c5c.png)

![image](https://user-images.githubusercontent.com/1287509/66978696-c9d13080-f05f-11e9-8efa-3a17b89e8ce2.png)

**Comment by akurzhan** [comment]
Percentages are applied, but they are normalized to 100. If you save this file, then load it you'll see 100% instead of 50%.  When percentages do not sum up to 100, they are normalized.
