### ISSUE TITLE
Controller settings

### ISSUE THREAD

**Issue by akurzhan** [ucbtrans/opt#39]
Generic controller parameters:
- start time
- end time
- dt
(all specified in seconds)

Ramp meter parameter:
- queue control - present or not?
- min rate
- max rate
Question: can we set different ramp metering controllers for different lane groups?

TOD controller:
- Metering rate - single value

Alinea controller
- upstream or downstream measurement reading
Question: we can specify a link (and offset) from where we will take the measurement - this is more general. Makes sense?

**Comment by ggomes** [comment]
Here is the API below. I will work out the implementation (reading/writing XML). You can start developing against the API though.

**Generic controller (ramp metering or policy)**

	public long getId() 
	public float getDt() 
	public void setDt(float dt) 
	public float getStartTime() 
	public void setStartTime(float start_time) 
	public float getEndTime() 
	public void setEndTime(float end_time) 
	public String getAlgorithm()
	public void setAlgorithm(String algorithm)

**Generic ramp metering controller**

    public boolean isHas_queue_control() 
    public void setHas_queue_control(boolean has_queue_control) 
    public float getMin_rate_vph() 
    public void setMin_rate_vph(float min_rate_vph) 
    public float getMax_rate_vph() 
    public void setMax_rate_vph(float max_rate_vph)
	
**ControllerRampMeterTOD** 

	public void clear_entries()
	public void add_entry(float time,float rate_vph)
	public void remove_entry(float time,float rate_vph) 
	public List<TODEntry> get_entries()  [class TODEntry contains float time and float rate_vph]

**ControllerRampMeterAlinea**
	public long getSensor_link_id() 
	public void setSensor_link_id(long sensor_link_id) 
	public float getSensor_offset_m() 
	public void setSensor_offset_m(float sensor_offset_m)
