### ISSUE TITLE
Road segments - names and implementation

### ISSUE THREAD

**Issue by akurzhan** [ucbtrans/opt#4]
Presently, road segments do not have names, just sequence numbers.
Current implementation does not allow networks. 
I'd like to revisit segments. Much more appealing to me right now is getting links and nodes from OTM, rather than these segments. 
If we continue with segments, things will get ugly very soon.

**Comment by ggomes** [comment]
Let's talk about this over the phone...

**Comment by ggomes** [comment]
I will open road segment names as a separate issue.

**Comment by ggomes** [comment]
The road segment names issue has been resolved. 
We will talk about potential problems with segments...
