### ISSUE TITLE
Saving routes in XML

### ISSUE THREAD

**Issue by akurzhan** [ucbtrans/opt#52]
I need API to save sequences of links (or road sections). Such a sequence represents a route. A route is a subnetwork.
A route must have a name. And, it is expected that a route (subnetwork) has an ID.
These routes (subnetworks) should be saved in some constant order - every time I load an .opt file, routes should be listed in the same order.

Suggested API:
- create new route - generates subnetwork/route object with ID and empty subnetwork
- delete route by ID
- set an ordered list of links (or road sections) on a route
- get an ordered list of links from a route
- get/set name on a route

**Comment by ggomes** [comment]
I've pushed the implementation of routes. Below are the API methods. I've put a sample route into project.opt. 

**FreewayScenario**
```
-     Route create_route(String name)
-     void delete_route(long routeid) throws Exception 
-     Collection<Route> get_routes()
-     Route get_route(long routeid)
```

**Route**
```
-     long getId()
-     List<Long> get_segment_ids() 
-     void add_segment_ids(List<Long> segmentids) 
-     void add_segment(Segment segment) 
-     void remove_segment_ids(Set<Long> segmentids) throws Exception 
-     void remove_segment(Segment segment) throws Exception 
-     void setName(String name) 
-     String getName() 
```
