### ISSUE TITLE
Loading links and segments

### ISSUE THREAD

**Issue by akurzhan** [ucbtrans/opt#53]
For the attached file (`.opt` is inside the `.zip`), scenario loader loads only one segment, although there are more.
It seems that `FreewayScenario.get_linear_freeway_segments()` reads `segments` variable, which already has just one segment. Info gets lost during loading of the config file.

[sample.zip](https://github.com/ucbtrans/opt/files/4625369/sample.zip)

**Comment by ggomes** [comment]
pushed a fix
