### ISSUE TITLE
Creation of on-ramps in NEW project

### ISSUE THREAD

**Issue by akurzhan** [ucbtrans/opt#62]
Scenario:

1.  Launch OPT and start new project Ctrl+N
2. Add  an on-ramp to section "A -> B"
3. Navigate to that on-ramp 
4. Yo will get at opt.config.LinkEditorController.refreshControllerList(LinkEditorController.java:2094) exception.

Reason: controller schedule does not find this on-ramp.

If you open an existing project and add new on-ramps to sections, all works fine.
This is an issue just for new projects.

**Comment by ggomes** [comment]
fixed with commit 4a2efa76ca9cfe8c9f176ce26520bd72bbc72ec8
