### ISSUE TITLE
NaN Traffic Demand

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#78]
Add Traffic Demand on Mainline (however do not define the % of commodities)
![image](https://user-images.githubusercontent.com/60490284/86033117-48eb7680-b9ed-11ea-946b-3eb427419056.png)

Run Simulation
Go to see again the Traffic Demand
The Traffic Demand became NaN
![image](https://user-images.githubusercontent.com/60490284/86033026-26595d80-b9ed-11ea-99ee-21f88136e4b0.png)

**Comment by ggomes** [comment]
Also, the normalization of the percentages should happen immediately after editing the values -- you shouldn't have to leave the Traffic Demands editor and return.
