### ISSUE TITLE
simulation speed

### ISSUE THREAD

**Issue by akurzhan** [ucbtrans/opt#87]
A decision about the simulation model must be made. 

Time of execution of the basic I-210E model - 24 hours with just GP lanes  and no control - is on average **146 seconds**. Reporting period of 5, 15, or 60 minutes makes virtually no difference in execution time. This is too long.

Execution time of I-210E model - also 24 hours with an HOV lane (and HOV control) and ramp metering in BeATS - is on average **30 seconds**.

**Comment by ggomes** [comment]
consolidated into issue 127
