### ISSUE TITLE
Link API - functions needed!

### ISSUE THREAD

**Issue by akurzhan** [ucbtrans/opt#9]
Gabriel,

For links I need the following functions:
- Access to predecessors and successors - add/remove (or get/set?)
- Get/set type. I really operate only on the level of AbstractLink, so just add a type parameter?
- Begin/end coordinates - so I could visualize the network (not for editing, just for displaying).

**Comment by ggomes** [comment]
Get type is there. You should not need set type or add/remove links or coordinates at this stage. Let's figure this out. Please push your code.
